sudo: false
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
  - ru-version
  - master
before_script:
  - npm install yaspeller -g
  - cargo install mdbook --force || true
script:
  - yaspeller --only-errors src/**/*.md
  - mdbook build
  - mdbook test
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
