sudo: false
language: rust
cache: cargo
rust:
  - nightly
branches:
  only:
  - ru_version
before_script:
  - npm install yaspeller -g
  - cargo install mdbook --force || true
script:
  - yaspeller --only-errors src/**/*.md
  - mdbook build
  - mdbook test
